# Generated by Django 5.1.6 on 2025-03-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_text", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="general_videos/"
                    ),
                ),
                ("scholarship_activity", models.BooleanField(default=False)),
            ],
        ),
    ]
