"""
Django settings for turing_back project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from turing_back.config import config

# -------------------------------#


BASE_DIR = Path(__file__).resolve().parent.parent.parent  # !! 3x .parent
# SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "fallback-secret-key")
SECRET_KEY = config.secret_key

#################################
#------------TELEGRAM-----------#
#################################
TELEGRAM_BOT_TOKEN = config.telegram_bot_token
CHAT_ID = config.telegram_contact_admin


#################################
# --------------APPS-------------#
#################################
LOCAL_APPS = [
    'turing_back.apps.api.v1.event',
    'turing_back.apps.api.v1.partner',
    'turing_back.apps.api.v1.general',
    'turing_back.apps.api.v1.graduate',
    'turing_back.apps.api.v1.community',
    'turing_back.apps.api.v1.speciality',
    'turing_back.apps.api.v1.schoolarship',
    'turing_back.apps.api.v1.test_and_contact',
]

THIRD_PART_APPS = [
    "rest_framework",  # for REST API
    "django_alive",  # for Monitoring
    "drf_yasg", # for Swagger

    "corsheaders", # Development
]

INSTALLED_APPS = (
    [
        "jazzmin",  # Third Part APP, but admin
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
    ]
    + THIRD_PART_APPS
    + LOCAL_APPS
)


# -------------------------------#
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", # cors
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# -------------------------------#
ROOT_URLCONF = "turing_back.urls"
WSGI_APPLICATION = "turing_back.wsgi.application"
# -------------------------------#


#################################
# -----------Databases-----------#
#################################
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "databases/core/db.sqlite3",
    },
}



# -------------------------------#
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]





LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True
STATIC_URL = "static/"
STATIC_ROOT = "statics/"
STATICFILES_DIRS = [
    BASE_DIR / "turing_back/static",
]
MEDIA_URL = "media/"
MEDIA_ROOT = "media/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#################################
# ------------TEMPLATES----------#
#################################
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "turing_back/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

#################################
# -----JAZZMIN Admin Settings----#
#################################
JAZZMIN_SETTINGS = {
    "site_title": "",
    "site_header": "turing_back",
    "site_brand": "turing_back",
    "site_logo": "logo/cc.jpg",
    "login_logo": "logo/cc.jpg",
    "login_logo_dark": "logo/cc.jpg",
    "site_logo_classes": "img-circle",
    "site_icon": "logo/cc.jpg",
    "welcome_sign": "Welcome to the turing_back Dashboard",
    "copyright": "Qiyas CC",
    "search_model": ["auth.User", "auth.Group"],
    "user_avatar": None,
    ############
    # Top Menu #
    ############
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {
            "name": "Support",
            "url": "https://github.com/qiyascc/django-layout",
            "new_window": True,
        },
        {"model": "auth.User"},
    ],
    #############
    # User Menu #
    #############
    "usermenu_links": [
        {
            "name": "Support",
            "url": "https://github.com/qiyascc/django-layout",
            "new_window": True,
        },
        {"model": "auth.user"},
    ],
    #############
    # Side Menu #
    #############
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "auth",
    ],
    "custom_links": {},
    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    #################
    # Related Modal #
    #################
    "related_modal_active": False,
    #############
    # UI Tweaks #
    #############
    "custom_css": 'admin/css/style.css',
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": False,
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": "cyborg",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# SWAGGER_SETTINGS = {
#     'SECURITY_DEFINITIONS': {
#         'Basic': {
#             'type': 'basic'
#         }
#     },
#     'USE_SESSION_AUTH': False,
# }