# Generated by Django 5.1.6 on 2025-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolarship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutprogram",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
