# Generated by Django 5.1.6 on 2025-03-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_and_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answer_type',
            field=models.CharField(choices=[('options', 'Qapalı sual - variantlı (variantlar üçün tab dəyişdirin)'), ('text', 'Açıq sual - aşağıda nə qədər minimum yazı limiti var onu qeyd edin (simvol kimi)')], max_length=10),
        ),
    ]
