# Generated by Django 5.1.6 on 2025-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="partner_images/")),
            ],
        ),
    ]
