# Generated by Django 5.1.6 on 2025-03-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chosenby",
            options={
                "verbose_name": "Bizi seçənlər",
                "verbose_name_plural": "Bizi seçənlər",
            },
        ),
        migrations.AlterModelOptions(
            name="we",
            options={
                "verbose_name": "Bizim fəaliyyətlərimiz",
                "verbose_name_plural": "Bizim fəaliyyətlərimiz",
            },
        ),
        migrations.RenameField(
            model_name="we",
            old_name="description_title",
            new_name="description",
        ),
        migrations.AddField(
            model_name="we",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
