# Generated by Django 5.1.6 on 2025-03-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_chosenby_options_alter_we_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="community",
            options={"verbose_name": "Community", "verbose_name_plural": "Community"},
        ),
    ]
