# Generated by Django 5.1.6 on 2025-03-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("speciality", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FAQ",
            new_name="SpecialityFAQ",
        ),
    ]
